"""Generates lib/core/l10n/app_strings.dart from the table below.
Add a language: add a new column + a Locale in supportedLocales. Then run:
python3 tool/gen_strings.py"""
import pathlib
T = {
 'appName': ('SaralBook', 'सरलबुक'),
 'navHome': ('Home', 'होम'), 'navStudy': ('Study', 'पढ़ाई'), 'navJobs': ('Jobs', 'नौकरियां'),
 'navTools': ('Tools', 'टूल्स'), 'navMore': ('More', 'अधिक'),
 'loading': ('Loading...', 'लोड हो रहा है...'),
 'exploreTitle': ('Explore SaralBook', 'सरलबुक एक्सप्लोर करें'),
 'exploreSubtitle': ('All our platforms in one app', 'हमारे सभी प्लेटफ़ॉर्म एक ही ऐप में'),
 'open': ('Open', 'खोलें'), 'refresh': ('Refresh', 'रीफ़्रेश'),
 'switchWebsite': ('Switch Website', 'वेबसाइट बदलें'),
 'noInternetTitle': ('No Internet Connection', 'इंटरनेट कनेक्शन नहीं है'),
 'noInternetMessage': ('Please check your internet connection and try again.', 'कृपया अपना इंटरनेट कनेक्शन जांचें और फिर कोशिश करें।'),
 'tryAgain': ('Try Again', 'फिर कोशिश करें'),
 'pageErrorTitle': ('Unable to load page', 'पेज लोड नहीं हो सका'),
 'pageErrorMessage': ('Something went wrong while loading. Please try again.', 'लोड करते समय कुछ गड़बड़ हुई। कृपया फिर कोशिश करें।'),
 'studyTitle': ('Study', 'पढ़ाई'),
 'studySubtitle': ('Study material, mock tests and learning resources', 'अध्ययन सामग्री, मॉक टेस्ट और लर्निंग संसाधन'),
 'jobsTitle': ('Jobs', 'नौकरियां'),
 'jobsSubtitle': ('Latest jobs, admit cards and results', 'ताज़ा नौकरियां, एडमिट कार्ड और रिज़ल्ट'),
 'toolsTitle': ('Tools', 'टूल्स'),
 'toolsSubtitle': ('Calculators and everyday tools', 'कैलकुलेटर और रोज़मर्रा के टूल्स'),
 'comingSoonTitle': ('Coming soon', 'जल्द आ रहा है'),
 'comingSoonStudy': ('Notes, to-do list, study planner and progress tracking will appear here.', 'नोट्स, टू-डू लिस्ट, स्टडी प्लानर और प्रोग्रेस ट्रैकिंग यहां दिखाई देंगे।'),
 'comingSoonJobs': ('Job alerts, bookmarks and notification preferences will appear here.', 'जॉब अलर्ट, बुकमार्क और नोटिफ़िकेशन सेटिंग्स यहां दिखाई देंगी।'),
 'comingSoonTools': ('Notes, to-do list, study planner and expense tracker arrive with Google sign-in.', 'नोट्स, टू-डू लिस्ट, स्टडी प्लानर और खर्च ट्रैकर Google साइन-इन के साथ आएंगे।'),
 'moreTitle': ('More', 'अधिक'),
 'appearance': ('Appearance', 'दिखावट'),
 'theme': ('Theme', 'थीम'), 'themeSystem': ('System', 'सिस्टम'),
 'themeLight': ('Light', 'लाइट'), 'themeDark': ('Dark', 'डार्क'),
 'language': ('Language', 'भाषा'),
 'aboutApp': ('About App', 'ऐप के बारे में'),
 'privacyPolicy': ('Privacy Policy', 'गोपनीयता नीति'),
 'terms': ('Terms & Conditions', 'नियम और शर्तें'),
 'contact': ('Contact', 'संपर्क'),
 'shareApp': ('Share App', 'ऐप शेयर करें'),
 'rateApp': ('Rate App', 'ऐप को रेट करें'),
 'version': ('Version', 'संस्करण'),
 'platformsTitle': ('Our Platforms', 'हमारे प्लेटफ़ॉर्म'),
 'recentTitle': ('Recently Viewed', 'हाल ही में देखा'),
 'recentEmpty': ('Pages you open will appear here.', 'आप जो पेज खोलेंगे वे यहां दिखेंगे।'),
 'feedEmpty': ('No updates right now.', 'अभी कोई अपडेट नहीं है।'),
 'feedError': ('Could not load updates.', 'अपडेट लोड नहीं हो सके।'),
 'feedOffline': ('You are offline.', 'आप ऑफ़लाइन हैं।'),
 'savedCopy': ('Showing saved copy', 'सहेजी हुई कॉपी दिखाई जा रही है'),
 'serviceUnavailableTitle': ('Service temporarily unavailable', 'सेवा अस्थायी रूप से उपलब्ध नहीं है'),
 'serviceUnavailableMessage': ('This service is not available right now. The rest of the app still works. Please try again later.', 'यह सेवा अभी उपलब्ध नहीं है। ऐप के बाकी हिस्से काम करते रहेंगे। कृपया बाद में फिर कोशिश करें।'),
 'unavailable': ('Unavailable', 'अनुपलब्ध'),
 'customizeHome': ('Customize Home', 'होम कस्टमाइज़ करें'),
 'customizeHint': ('Show, hide and reorder sections', 'सेक्शन दिखाएं, छिपाएं और क्रम बदलें'),
 'resetDefault': ('Reset to default', 'डिफ़ॉल्ट पर रीसेट करें'),
 'dataStorage': ('Data & storage', 'डेटा और स्टोरेज'),
 'clearCache': ('Clear cache', 'कैश साफ़ करें'),
 'clearCacheHint': ('Removes saved updates stored on this phone', 'इस फ़ोन पर सहेजे गए अपडेट हटाता है'),
 'cacheCleared': ('Cache cleared', 'कैश साफ़ किया गया'),
 'maintenanceTitle': ('Under maintenance', 'रखरखाव जारी है'),
 'maintenanceMessage': ('We will be back shortly.', 'हम जल्द वापस आएंगे।'),
 'toolsSearchHint': ('Search tools', 'टूल खोजें'),
 'noToolsFound': ('No tools match your search.', 'आपकी खोज से कोई टूल नहीं मिला।'),
 'enterValues': ('Enter values to see the result.', 'परिणाम देखने के लिए मान दर्ज करें।'),
 'resultTitle': ('Result', 'परिणाम'),
 'selectDate': ('Select date', 'तारीख चुनें'),
 'clear': ('Clear', 'हटाएं'),
 'start': ('Start', 'शुरू करें'),
 'pause': ('Pause', 'रोकें'),
 'resume': ('Resume', 'जारी रखें'),
 'reset': ('Reset', 'रीसेट'),
 'lap': ('Lap', 'लैप'),
 'focus': ('Focus', 'फ़ोकस'),
 'shortBreak': ('Short break', 'छोटा ब्रेक'),
 'longBreak': ('Long break', 'लंबा ब्रेक'),
 'sessionsDone': ('Focus sessions done', 'पूरे हुए फ़ोकस सेशन'),
 'onlineToolsTitle': ('More tools online', 'ऑनलाइन और टूल्स'),
 'catExamCalc': ('Exam Calculators', 'परीक्षा कैलकुलेटर'),
 'catStudent': ('Student Tools', 'स्टूडेंट टूल्स'),
 'catExamJob': ('Exam & Job Tools', 'परीक्षा और नौकरी टूल्स'),
 'stopwatchTitle': ('Stopwatch', 'स्टॉपवॉच'),
 'pomodoroTitle': ('Pomodoro Timer', 'पोमोडोरो टाइमर'),
 'stopwatchDesc': ('Time yourself with laps', 'लैप के साथ समय नापें'),
 'pomodoroDesc': ('25-minute focus sessions with breaks', 'ब्रेक के साथ 25 मिनट के फ़ोकस सेशन'),
 'catFiles': ('PDF & Image Tools', 'PDF और इमेज टूल्स'),
 'cancel': ('Cancel', 'रद्द करें'),
 'accountTitle': ('Account', 'अकाउंट'),
 'signInGoogle': ('Sign in with Google', 'Google से साइन इन करें'),
 'signInBenefit': ('Sign in to save notes, to-do lists, study plans and expenses and use them on any phone. The rest of the app works without signing in.', 'नोट्स, टू-डू लिस्ट, स्टडी प्लान और खर्च सेव करने और किसी भी फ़ोन पर इस्तेमाल करने के लिए साइन इन करें। ऐप का बाकी हिस्सा बिना साइन इन के भी चलता है।'),
 'signOut': ('Sign out', 'साइन आउट'),
 'signOutConfirm': ('Sign out of this account? Your data stays safe in the cloud.', 'इस अकाउंट से साइन आउट करें? आपका डेटा क्लाउड में सुरक्षित रहेगा।'),
 'switchAccount': ('Switch account', 'अकाउंट बदलें'),
 'signingIn': ('Signing in...', 'साइन इन हो रहा है...'),
 'signInCancelled': ('Sign-in cancelled', 'साइन-इन रद्द किया गया'),
 'signInFailed': ('Could not sign in. Check your internet and try again.', 'साइन इन नहीं हो सका। इंटरनेट जांचें और फिर कोशिश करें।'),
 'signInUnavailable': ('Sign-in is not available in this version right now.', 'इस वर्ज़न में साइन-इन अभी उपलब्ध नहीं है।'),
 'signedOutDone': ('Signed out', 'साइन आउट हो गया'),
 'googleHelp': ('Google account help', 'Google अकाउंट सहायता'),
 'manageGoogle': ('Manage Google account', 'Google अकाउंट मैनेज करें'),
 'createGoogle': ('Create a Google account', 'Google अकाउंट बनाएं'),
 'openGmail': ('Open Gmail', 'Gmail खोलें'),
 'recoverAccount': ('Forgot password / recover account', 'पासवर्ड भूल गए / अकाउंट रिकवर करें'),
 'signInRequiredTitle': ('Sign in required', 'साइन इन ज़रूरी है'),
 'signInRequiredBody': ('Please sign in with Google to use this feature. Your data stays separate for each account.', 'इस सुविधा के लिए कृपया Google से साइन इन करें। हर अकाउंट का डेटा अलग रहता है।'),
 'signedInStudyNote': ('You are signed in. Notes, to-do and study planner are coming next.', 'आप साइन इन हैं। नोट्स, टू-डू और स्टडी प्लानर जल्द आ रहे हैं।'),
}
LANGS = ['en', 'hi']
def q(s): return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"
out = ["// GENERATED by tool/gen_strings.py - edit the table there, not this file.",
       "import 'package:flutter/foundation.dart';",
       "import 'package:flutter/widgets.dart';", "",
       "class AppStrings {",
       "  AppStrings(this.locale);", "  final Locale locale;", "",
       "  static const List<Locale> supportedLocales = [%s];" % ', '.join("Locale('%s')" % l for l in LANGS),
       "  static const LocalizationsDelegate<AppStrings> delegate = _AppStringsDelegate();", "",
       "  static AppStrings of(BuildContext context) =>",
       "      Localizations.of<AppStrings>(context, AppStrings) ??",
       "      AppStrings(const Locale('en'));", "",
       "  static Map<String, String> valuesFor(String languageCode) =>",
       "      _values[languageCode] ?? const <String, String>{};", "",
       "  String _t(String key) =>",
       "      _values[locale.languageCode]?[key] ?? _values['en']![key] ?? key;", ""]
for k in T: out.append("  String get %s => _t(%s);" % (k, q(k)))
out += ["", "  static const Map<String, Map<String, String>> _values = {"]
for i, l in enumerate(LANGS):
    out.append("    %s: {" % q(l))
    for k, v in T.items(): out.append("      %s: %s," % (q(k), q(v[i])))
    out.append("    },")
out += ["  };", "}", "",
 "class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {",
 "  const _AppStringsDelegate();", "",
 "  @override",
 "  bool isSupported(Locale locale) => AppStrings.supportedLocales",
 "      .any((l) => l.languageCode == locale.languageCode);", "",
 "  @override",
 "  Future<AppStrings> load(Locale locale) =>",
 "      SynchronousFuture<AppStrings>(AppStrings(locale));", "",
 "  @override",
 "  bool shouldReload(_AppStringsDelegate old) => false;",
 "}", ""]
pathlib.Path('lib/core/l10n/app_strings.dart').write_text('\n'.join(out))
print('generated', len(T), 'keys x', len(LANGS), 'languages')
