// GENERATED by tool/gen_strings.py - edit the table there, not this file.
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

class AppStrings {
  AppStrings(this.locale);
  final Locale locale;

  static const List<Locale> supportedLocales = [Locale('en'), Locale('hi')];
  static const LocalizationsDelegate<AppStrings> delegate = _AppStringsDelegate();

  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings) ??
      AppStrings(const Locale('en'));

  static Map<String, String> valuesFor(String languageCode) =>
      _values[languageCode] ?? const <String, String>{};

  String _t(String key) =>
      _values[locale.languageCode]?[key] ?? _values['en']![key] ?? key;

  String get appName => _t('appName');
  String get navHome => _t('navHome');
  String get navStudy => _t('navStudy');
  String get navJobs => _t('navJobs');
  String get navTools => _t('navTools');
  String get navMore => _t('navMore');
  String get loading => _t('loading');
  String get exploreTitle => _t('exploreTitle');
  String get exploreSubtitle => _t('exploreSubtitle');
  String get open => _t('open');
  String get refresh => _t('refresh');
  String get switchWebsite => _t('switchWebsite');
  String get noInternetTitle => _t('noInternetTitle');
  String get noInternetMessage => _t('noInternetMessage');
  String get tryAgain => _t('tryAgain');
  String get pageErrorTitle => _t('pageErrorTitle');
  String get pageErrorMessage => _t('pageErrorMessage');
  String get studyTitle => _t('studyTitle');
  String get studySubtitle => _t('studySubtitle');
  String get jobsTitle => _t('jobsTitle');
  String get jobsSubtitle => _t('jobsSubtitle');
  String get toolsTitle => _t('toolsTitle');
  String get toolsSubtitle => _t('toolsSubtitle');
  String get comingSoonTitle => _t('comingSoonTitle');
  String get comingSoonStudy => _t('comingSoonStudy');
  String get comingSoonJobs => _t('comingSoonJobs');
  String get comingSoonTools => _t('comingSoonTools');
  String get moreTitle => _t('moreTitle');
  String get appearance => _t('appearance');
  String get theme => _t('theme');
  String get themeSystem => _t('themeSystem');
  String get themeLight => _t('themeLight');
  String get themeDark => _t('themeDark');
  String get language => _t('language');
  String get aboutApp => _t('aboutApp');
  String get privacyPolicy => _t('privacyPolicy');
  String get terms => _t('terms');
  String get contact => _t('contact');
  String get shareApp => _t('shareApp');
  String get rateApp => _t('rateApp');
  String get version => _t('version');
  String get platformsTitle => _t('platformsTitle');
  String get recentTitle => _t('recentTitle');
  String get recentEmpty => _t('recentEmpty');
  String get feedEmpty => _t('feedEmpty');
  String get feedError => _t('feedError');
  String get feedOffline => _t('feedOffline');
  String get savedCopy => _t('savedCopy');
  String get serviceUnavailableTitle => _t('serviceUnavailableTitle');
  String get serviceUnavailableMessage => _t('serviceUnavailableMessage');
  String get unavailable => _t('unavailable');
  String get customizeHome => _t('customizeHome');
  String get customizeHint => _t('customizeHint');
  String get resetDefault => _t('resetDefault');
  String get dataStorage => _t('dataStorage');
  String get clearCache => _t('clearCache');
  String get clearCacheHint => _t('clearCacheHint');
  String get cacheCleared => _t('cacheCleared');
  String get maintenanceTitle => _t('maintenanceTitle');
  String get maintenanceMessage => _t('maintenanceMessage');
  String get toolsSearchHint => _t('toolsSearchHint');
  String get noToolsFound => _t('noToolsFound');
  String get enterValues => _t('enterValues');
  String get resultTitle => _t('resultTitle');
  String get selectDate => _t('selectDate');
  String get clear => _t('clear');
  String get start => _t('start');
  String get pause => _t('pause');
  String get resume => _t('resume');
  String get reset => _t('reset');
  String get lap => _t('lap');
  String get focus => _t('focus');
  String get shortBreak => _t('shortBreak');
  String get longBreak => _t('longBreak');
  String get sessionsDone => _t('sessionsDone');
  String get onlineToolsTitle => _t('onlineToolsTitle');
  String get catExamCalc => _t('catExamCalc');
  String get catStudent => _t('catStudent');
  String get catExamJob => _t('catExamJob');
  String get stopwatchTitle => _t('stopwatchTitle');
  String get pomodoroTitle => _t('pomodoroTitle');
  String get stopwatchDesc => _t('stopwatchDesc');
  String get pomodoroDesc => _t('pomodoroDesc');
  String get catFiles => _t('catFiles');
  String get cancel => _t('cancel');
  String get accountTitle => _t('accountTitle');
  String get signInGoogle => _t('signInGoogle');
  String get signInBenefit => _t('signInBenefit');
  String get signOut => _t('signOut');
  String get signOutConfirm => _t('signOutConfirm');
  String get switchAccount => _t('switchAccount');
  String get signingIn => _t('signingIn');
  String get signInCancelled => _t('signInCancelled');
  String get signInFailed => _t('signInFailed');
  String get signInUnavailable => _t('signInUnavailable');
  String get signedOutDone => _t('signedOutDone');
  String get googleHelp => _t('googleHelp');
  String get manageGoogle => _t('manageGoogle');
  String get createGoogle => _t('createGoogle');
  String get openGmail => _t('openGmail');
  String get recoverAccount => _t('recoverAccount');
  String get signInRequiredTitle => _t('signInRequiredTitle');
  String get signInRequiredBody => _t('signInRequiredBody');
  String get signedInStudyNote => _t('signedInStudyNote');

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'appName': 'SaralBook',
      'navHome': 'Home',
      'navStudy': 'Study',
      'navJobs': 'Jobs',
      'navTools': 'Tools',
      'navMore': 'More',
      'loading': 'Loading...',
      'exploreTitle': 'Explore SaralBook',
      'exploreSubtitle': 'All our platforms in one app',
      'open': 'Open',
      'refresh': 'Refresh',
      'switchWebsite': 'Switch Website',
      'noInternetTitle': 'No Internet Connection',
      'noInternetMessage': 'Please check your internet connection and try again.',
      'tryAgain': 'Try Again',
      'pageErrorTitle': 'Unable to load page',
      'pageErrorMessage': 'Something went wrong while loading. Please try again.',
      'studyTitle': 'Study',
      'studySubtitle': 'Study material, mock tests and learning resources',
      'jobsTitle': 'Jobs',
      'jobsSubtitle': 'Latest jobs, admit cards and results',
      'toolsTitle': 'Tools',
      'toolsSubtitle': 'Calculators and everyday tools',
      'comingSoonTitle': 'Coming soon',
      'comingSoonStudy': 'Notes, to-do list, study planner and progress tracking will appear here.',
      'comingSoonJobs': 'Job alerts, bookmarks and notification preferences will appear here.',
      'comingSoonTools': 'Notes, to-do list, study planner and expense tracker arrive with Google sign-in.',
      'moreTitle': 'More',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'themeSystem': 'System',
      'themeLight': 'Light',
      'themeDark': 'Dark',
      'language': 'Language',
      'aboutApp': 'About App',
      'privacyPolicy': 'Privacy Policy',
      'terms': 'Terms & Conditions',
      'contact': 'Contact',
      'shareApp': 'Share App',
      'rateApp': 'Rate App',
      'version': 'Version',
      'platformsTitle': 'Our Platforms',
      'recentTitle': 'Recently Viewed',
      'recentEmpty': 'Pages you open will appear here.',
      'feedEmpty': 'No updates right now.',
      'feedError': 'Could not load updates.',
      'feedOffline': 'You are offline.',
      'savedCopy': 'Showing saved copy',
      'serviceUnavailableTitle': 'Service temporarily unavailable',
      'serviceUnavailableMessage': 'This service is not available right now. The rest of the app still works. Please try again later.',
      'unavailable': 'Unavailable',
      'customizeHome': 'Customize Home',
      'customizeHint': 'Show, hide and reorder sections',
      'resetDefault': 'Reset to default',
      'dataStorage': 'Data & storage',
      'clearCache': 'Clear cache',
      'clearCacheHint': 'Removes saved updates stored on this phone',
      'cacheCleared': 'Cache cleared',
      'maintenanceTitle': 'Under maintenance',
      'maintenanceMessage': 'We will be back shortly.',
      'toolsSearchHint': 'Search tools',
      'noToolsFound': 'No tools match your search.',
      'enterValues': 'Enter values to see the result.',
      'resultTitle': 'Result',
      'selectDate': 'Select date',
      'clear': 'Clear',
      'start': 'Start',
      'pause': 'Pause',
      'resume': 'Resume',
      'reset': 'Reset',
      'lap': 'Lap',
      'focus': 'Focus',
      'shortBreak': 'Short break',
      'longBreak': 'Long break',
      'sessionsDone': 'Focus sessions done',
      'onlineToolsTitle': 'More tools online',
      'catExamCalc': 'Exam Calculators',
      'catStudent': 'Student Tools',
      'catExamJob': 'Exam & Job Tools',
      'stopwatchTitle': 'Stopwatch',
      'pomodoroTitle': 'Pomodoro Timer',
      'stopwatchDesc': 'Time yourself with laps',
      'pomodoroDesc': '25-minute focus sessions with breaks',
      'catFiles': 'PDF & Image Tools',
      'cancel': 'Cancel',
      'accountTitle': 'Account',
      'signInGoogle': 'Sign in with Google',
      'signInBenefit': 'Sign in to save notes, to-do lists, study plans and expenses and use them on any phone. The rest of the app works without signing in.',
      'signOut': 'Sign out',
      'signOutConfirm': 'Sign out of this account? Your data stays safe in the cloud.',
      'switchAccount': 'Switch account',
      'signingIn': 'Signing in...',
      'signInCancelled': 'Sign-in cancelled',
      'signInFailed': 'Could not sign in. Check your internet and try again.',
      'signInUnavailable': 'Sign-in is not available in this version right now.',
      'signedOutDone': 'Signed out',
      'googleHelp': 'Google account help',
      'manageGoogle': 'Manage Google account',
      'createGoogle': 'Create a Google account',
      'openGmail': 'Open Gmail',
      'recoverAccount': 'Forgot password / recover account',
      'signInRequiredTitle': 'Sign in required',
      'signInRequiredBody': 'Please sign in with Google to use this feature. Your data stays separate for each account.',
      'signedInStudyNote': 'You are signed in. Notes, to-do and study planner are coming next.',
    },
    'hi': {
      'appName': 'सरलबुक',
      'navHome': 'होम',
      'navStudy': 'पढ़ाई',
      'navJobs': 'नौकरियां',
      'navTools': 'टूल्स',
      'navMore': 'अधिक',
      'loading': 'लोड हो रहा है...',
      'exploreTitle': 'सरलबुक एक्सप्लोर करें',
      'exploreSubtitle': 'हमारे सभी प्लेटफ़ॉर्म एक ही ऐप में',
      'open': 'खोलें',
      'refresh': 'रीफ़्रेश',
      'switchWebsite': 'वेबसाइट बदलें',
      'noInternetTitle': 'इंटरनेट कनेक्शन नहीं है',
      'noInternetMessage': 'कृपया अपना इंटरनेट कनेक्शन जांचें और फिर कोशिश करें।',
      'tryAgain': 'फिर कोशिश करें',
      'pageErrorTitle': 'पेज लोड नहीं हो सका',
      'pageErrorMessage': 'लोड करते समय कुछ गड़बड़ हुई। कृपया फिर कोशिश करें।',
      'studyTitle': 'पढ़ाई',
      'studySubtitle': 'अध्ययन सामग्री, मॉक टेस्ट और लर्निंग संसाधन',
      'jobsTitle': 'नौकरियां',
      'jobsSubtitle': 'ताज़ा नौकरियां, एडमिट कार्ड और रिज़ल्ट',
      'toolsTitle': 'टूल्स',
      'toolsSubtitle': 'कैलकुलेटर और रोज़मर्रा के टूल्स',
      'comingSoonTitle': 'जल्द आ रहा है',
      'comingSoonStudy': 'नोट्स, टू-डू लिस्ट, स्टडी प्लानर और प्रोग्रेस ट्रैकिंग यहां दिखाई देंगे।',
      'comingSoonJobs': 'जॉब अलर्ट, बुकमार्क और नोटिफ़िकेशन सेटिंग्स यहां दिखाई देंगी।',
      'comingSoonTools': 'नोट्स, टू-डू लिस्ट, स्टडी प्लानर और खर्च ट्रैकर Google साइन-इन के साथ आएंगे।',
      'moreTitle': 'अधिक',
      'appearance': 'दिखावट',
      'theme': 'थीम',
      'themeSystem': 'सिस्टम',
      'themeLight': 'लाइट',
      'themeDark': 'डार्क',
      'language': 'भाषा',
      'aboutApp': 'ऐप के बारे में',
      'privacyPolicy': 'गोपनीयता नीति',
      'terms': 'नियम और शर्तें',
      'contact': 'संपर्क',
      'shareApp': 'ऐप शेयर करें',
      'rateApp': 'ऐप को रेट करें',
      'version': 'संस्करण',
      'platformsTitle': 'हमारे प्लेटफ़ॉर्म',
      'recentTitle': 'हाल ही में देखा',
      'recentEmpty': 'आप जो पेज खोलेंगे वे यहां दिखेंगे।',
      'feedEmpty': 'अभी कोई अपडेट नहीं है।',
      'feedError': 'अपडेट लोड नहीं हो सके।',
      'feedOffline': 'आप ऑफ़लाइन हैं।',
      'savedCopy': 'सहेजी हुई कॉपी दिखाई जा रही है',
      'serviceUnavailableTitle': 'सेवा अस्थायी रूप से उपलब्ध नहीं है',
      'serviceUnavailableMessage': 'यह सेवा अभी उपलब्ध नहीं है। ऐप के बाकी हिस्से काम करते रहेंगे। कृपया बाद में फिर कोशिश करें।',
      'unavailable': 'अनुपलब्ध',
      'customizeHome': 'होम कस्टमाइज़ करें',
      'customizeHint': 'सेक्शन दिखाएं, छिपाएं और क्रम बदलें',
      'resetDefault': 'डिफ़ॉल्ट पर रीसेट करें',
      'dataStorage': 'डेटा और स्टोरेज',
      'clearCache': 'कैश साफ़ करें',
      'clearCacheHint': 'इस फ़ोन पर सहेजे गए अपडेट हटाता है',
      'cacheCleared': 'कैश साफ़ किया गया',
      'maintenanceTitle': 'रखरखाव जारी है',
      'maintenanceMessage': 'हम जल्द वापस आएंगे।',
      'toolsSearchHint': 'टूल खोजें',
      'noToolsFound': 'आपकी खोज से कोई टूल नहीं मिला।',
      'enterValues': 'परिणाम देखने के लिए मान दर्ज करें।',
      'resultTitle': 'परिणाम',
      'selectDate': 'तारीख चुनें',
      'clear': 'हटाएं',
      'start': 'शुरू करें',
      'pause': 'रोकें',
      'resume': 'जारी रखें',
      'reset': 'रीसेट',
      'lap': 'लैप',
      'focus': 'फ़ोकस',
      'shortBreak': 'छोटा ब्रेक',
      'longBreak': 'लंबा ब्रेक',
      'sessionsDone': 'पूरे हुए फ़ोकस सेशन',
      'onlineToolsTitle': 'ऑनलाइन और टूल्स',
      'catExamCalc': 'परीक्षा कैलकुलेटर',
      'catStudent': 'स्टूडेंट टूल्स',
      'catExamJob': 'परीक्षा और नौकरी टूल्स',
      'stopwatchTitle': 'स्टॉपवॉच',
      'pomodoroTitle': 'पोमोडोरो टाइमर',
      'stopwatchDesc': 'लैप के साथ समय नापें',
      'pomodoroDesc': 'ब्रेक के साथ 25 मिनट के फ़ोकस सेशन',
      'catFiles': 'PDF और इमेज टूल्स',
      'cancel': 'रद्द करें',
      'accountTitle': 'अकाउंट',
      'signInGoogle': 'Google से साइन इन करें',
      'signInBenefit': 'नोट्स, टू-डू लिस्ट, स्टडी प्लान और खर्च सेव करने और किसी भी फ़ोन पर इस्तेमाल करने के लिए साइन इन करें। ऐप का बाकी हिस्सा बिना साइन इन के भी चलता है।',
      'signOut': 'साइन आउट',
      'signOutConfirm': 'इस अकाउंट से साइन आउट करें? आपका डेटा क्लाउड में सुरक्षित रहेगा।',
      'switchAccount': 'अकाउंट बदलें',
      'signingIn': 'साइन इन हो रहा है...',
      'signInCancelled': 'साइन-इन रद्द किया गया',
      'signInFailed': 'साइन इन नहीं हो सका। इंटरनेट जांचें और फिर कोशिश करें।',
      'signInUnavailable': 'इस वर्ज़न में साइन-इन अभी उपलब्ध नहीं है।',
      'signedOutDone': 'साइन आउट हो गया',
      'googleHelp': 'Google अकाउंट सहायता',
      'manageGoogle': 'Google अकाउंट मैनेज करें',
      'createGoogle': 'Google अकाउंट बनाएं',
      'openGmail': 'Gmail खोलें',
      'recoverAccount': 'पासवर्ड भूल गए / अकाउंट रिकवर करें',
      'signInRequiredTitle': 'साइन इन ज़रूरी है',
      'signInRequiredBody': 'इस सुविधा के लिए कृपया Google से साइन इन करें। हर अकाउंट का डेटा अलग रहता है।',
      'signedInStudyNote': 'आप साइन इन हैं। नोट्स, टू-डू और स्टडी प्लानर जल्द आ रहे हैं।',
    },
  };
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales
      .any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppStrings> load(Locale locale) =>
      SynchronousFuture<AppStrings>(AppStrings(locale));

  @override
  bool shouldReload(_AppStringsDelegate old) => false;
}
